#!/bin/bash
set -e


ACTIVEMQ_VERSION="5.14.3"
ACTIVEMQ_HOME="/opt/activemq"
SETUP_DIR="/app/setup"
LOG_DIR="/var/log"
DATA_DIR="/data"

# Start install
mkdir -p ${ACTIVEMQ_HOME}
cd /usr/src
curl -LO http://apache.mirrors.ovh.net/ftp.apache.org/dist/activemq/${ACTIVEMQ_VERSION}/apache-activemq-${ACTIVEMQ_VERSION}-bin.tar.gz
tar -xvzf apache-activemq-${ACTIVEMQ_VERSION}-bin.tar.gz
mv apache-activemq-${ACTIVEMQ_VERSION}/* ${ACTIVEMQ_HOME}
rm -rf /usr/src/*

cd /app
mkdir -p /data/activemq
mkdir -p /var/log/activemq
groupadd activemq
useradd --system --home ${ACTIVEMQ_HOME} -g activemq activemq


chown -R activemq:activemq ${ACTIVEMQ_HOME}
chown -R activemq:activemq ${DATA_DIR}/activemq
chown -R activemq:activemq ${LOG_DIR}/activemq





# configure supervisord to start activeMQ
cat > /etc/supervisor/conf.d/activemq.conf <<EOF
[program:activemq]
priority=20
directory=/tmp
command=/opt/activemq/bin/activemq console
user=root
autostart=true
autorestart=true
stdout_logfile=${LOG_DIR}/activemq/console.log
stderr_logfile=${LOG_DIR}/activemq/console.log
EOF
