#!/bin/bash

set -e

SETUP_DIR="/app/setup"
ACTIVEMQ_HOME="/opt/activemq"
ACTIVEMQ_DATA="/data/activemq"
ACTIVEMQ_CONF="${ACTIVEMQ_HOME}/conf"
ACTIVEMQ_LOG="/var/log/activemq"


# ActiveMQ setting
ACTIVEMQ_NAME=${ACTIVEMQ_NAME:-localhost}
ACTIVEMQ_LOGLEVEL=${ACTIVEMQ_LOGLEVEL:-INFO}
ACTIVEMQ_PENDING_MESSAGE_LIMIT=${ACTIVEMQ_PENDING_MESSAGE_LIMIT:-1000}
ACTIVEMQ_STORAGE_USAGE=${ACTIVEMQ_STORAGE_USAGE:-"100 gb"}
ACTIVEMQ_TEMP_USAGE=${ACTIVEMQ_TEMP_USAGE:-"50 gb"}
ACTIVEMQ_MAX_CONNECTION=${ACTIVEMQ_MAX_CONNECTION:-1000}
ACTIVEMQ_FRAME_SIZE=${ACTIVEMQ_FRAME_SIZE:-104857600}
ACTIVEMQ_MIN_MEMORY=${ACTIVEMQ_MIN_MEMORY:-128}
ACTIVEMQ_MAX_MEMORY=${ACTIVEMQ_MAX_MEMORY:-1024}

# Users settings
ACTIVEMQ_ADMIN_LOGIN=${ACTIVEMQ_ADMIN_LOGIN:-admin}
ACTIVEMQ_ADMIN_PASSWORD=${ACTIVEMQ_ADMIN_PASSWORD:-admin}
ACTIVEMQ_USER_LOGIN=${ACTIVEMQ_USER_LOGIN:-user}
ACTIVEMQ_USER_PASSWORD=${ACTIVEMQ_USER_PASSWORD:-user}
ACTIVEMQ_READ_LOGIN=${ACTIVEMQ_READ_LOGIN:-}
ACTIVEMQ_READ_PASSWORD=${ACTIVEMQ_READ_PASSWORD:-}
ACTIVEMQ_WRITE_LOGIN=${ACTIVEMQ_WRITE_LOGIN:-}
ACTIVEMQ_WRITE_PASSWORD=${ACTIVEMQ_WRITE_PASSWORD:-}
ACTIVEMQ_OWNER_LOGIN=${ACTIVEMQ_OWNER_LOGIN:-}
ACTIVEMQ_OWNER_PASSWORD=${ACTIVEMQ_OWNER_PASSWORD:-}
ACTIVEMQ_JMX_LOGIN=${ACTIVEMQ_JMX_LOGIN:-admin}
ACTIVEMQ_JMX_PASSWORD=${ACTIVEMQ_JMX_PASSWORD:-activemq}



# Topics and queues settings
ACTIVEMQ_STATIC_TOPICS=${ACTIVEMQ_STATIC_TOPICS:-}
ACTIVEMQ_STATIC_QUEUES=${ACTIVEMQ_STATIC_QUEUES:-}

# Clients setting
ACTIVEMQ_PERSISTENT_CLIENTS=ACTIVEMQ_PERSISTENT_CLIENT:-}

# We go on activemq directory
cd ${ACTIVEMQ_HOME}


# We setting the file users.properties (this permit to connect on topics and queues)
sudo -u activemq -H sed 's/{{ACTIVEMQ_ADMIN}}/'"${ACTIVEMQ_ADMIN_LOGIN}=${ACTIVEMQ_ADMIN_PASSWORD}"'/' -i conf/users.properties
sudo -u activemq -H sed 's/{{ACTIVEMQ_USER}}/'"${ACTIVEMQ_USER_LOGIN}=${ACTIVEMQ_USER_PASSWORD}"'/' -i conf/users.properties
if [ "${ACTIVEMQ_READ_LOGIN}X" != "X" ]; then
	sudo -u activemq -H sed 's/{{ACTIVEMQ_READ}}/'"${ACTIVEMQ_READ_LOGIN}=${ACTIVEMQ_READ_PASSWORD}"'/' -i conf/users.properties
else
	sudo -u activemq -H sed 's/{{ACTIVEMQ_READ}}/'""'/' -i conf/users.properties
fi
if [ "${ACTIVEMQ_WRITE_LOGIN}X" != "X" ]; then
	sudo -u activemq -H sed 's/{{ACTIVEMQ_WRITE}}/'"${ACTIVEMQ_WRITE_LOGIN}=${ACTIVEMQ_WRITE_PASSWORD}"'/' -i conf/users.properties
else
	sudo -u activemq -H sed 's/{{ACTIVEMQ_WRITE}}/'""'/' -i conf/users.properties
fi
if [ "${ACTIVEMQ_OWNER_LOGIN}X" != "X" ]; then
	sudo -u activemq -H sed 's/{{ACTIVEMQ_OWNER}}/'"${ACTIVEMQ_OWNER_LOGIN}=${ACTIVEMQ_OWNER_PASSWORD}"'/' -i conf/users.properties
else
	sudo -u activemq -H sed 's/{{ACTIVEMQ_OWNER}}/'""'/' -i conf/users.properties
fi

# We setting the file groups.properties (this permit to be on the right role to access on topics and queues)
sudo -u activemq -H sed 's/{{ACTIVEMQ_ADMIN_LOGIN}}/'"${ACTIVEMQ_ADMIN_LOGIN}"'/' -i conf/groups.properties
sudo -u activemq -H sed 's/{{ACTIVEMQ_READ_LOGIN}}/'"${ACTIVEMQ_READ_LOGIN}"'/' -i conf/groups.properties
sudo -u activemq -H sed 's/{{ACTIVEMQ_WRITE_LOGIN}}/'"${ACTIVEMQ_WRITE_LOGIN}"'/' -i conf/groups.properties
sudo -u activemq -H sed 's/{{ACTIVEMQ_OWNER_LOGIN}}/'"${ACTIVEMQ_OWNER_LOGIN}"'/' -i conf/groups.properties

# We setting the file jetty-realm.properties (this permit to acces on web console)
sudo -u activemq -H sed 's/{{ACTIVEMQ_ADMIN}}/'"${ACTIVEMQ_ADMIN_LOGIN}: ${ACTIVEMQ_ADMIN_PASSWORD}, admin"'/' -i conf/jetty-realm.properties
sudo -u activemq -H sed 's/{{ACTIVEMQ_USER}}/'"${ACTIVEMQ_USER_LOGIN}: ${ACTIVEMQ_USER_PASSWORD}, user"'/' -i conf/jetty-realm.properties

# We setting the file jmx.access and jmx.password (this permit to allow access on jmx)
sudo -u activemq -H sed 's/{{ACTIVEMQ_JMX_LOGIN}}/'"${ACTIVEMQ_JMX_LOGIN}"'/' -i conf/jmx.access
sudo -u activemq -H sed 's/{{ACTIVEMQ_JMX}}/'"${ACTIVEMQ_JMX_LOGIN} ${ACTIVEMQ_JMX_PASSWORD}"'/' -i conf/jmx.password

# We setting the file log4j.properties (this permit to change log level)
sudo -u activemq -H sed 's,{{ACTIVEMQ_LOGLEVEL}},'"${ACTIVEMQ_LOGLEVEL}"',g' -i conf/log4j.properties

# We setting the activemq.xml (this is the main setting of ActiveMQ)
sudo -u activemq -H sed 's/{{ACTIVEMQ_NAME}}/'"${ACTIVEMQ_NAME}"'/' -i conf/activemq.xml
sudo -u activemq -H sed 's/{{ACTIVEMQ_PENDING_MESSAGE_LIMIT}}/'"${ACTIVEMQ_PENDING_MESSAGE_LIMIT}"'/' -i conf/activemq.xml
sudo -u activemq -H sed 's/{{ACTIVEMQ_STORAGE_USAGE}}/'"${ACTIVEMQ_STORAGE_USAGE}"'/' -i conf/activemq.xml
sudo -u activemq -H sed 's/{{ACTIVEMQ_TEMP_USAGE}}/'"${ACTIVEMQ_TEMP_USAGE}"'/' -i conf/activemq.xml
sudo -u activemq -H sed 's,{{ACTIVEMQ_MAX_CONNECTION}},'"${ACTIVEMQ_MAX_CONNECTION}"',g' -i conf/activemq.xml
sudo -u activemq -H sed 's,{{ACTIVEMQ_FRAME_SIZE}},'"${ACTIVEMQ_FRAME_SIZE}"',g' -i conf/activemq.xml
ACTIVEMQ_PERSISTENT_TOPIC=""
ACTIVEMQ_PERSISTENT_QUEUE=""
if [ "${ACTIVEMQ_STATIC_TOPICS}X" != "X" ]; then
	TOPICS=$(echo ${ACTIVEMQ_STATIC_TOPICS} | tr ";" "\n")
	for x in ${TOPICS}
	do
		ACTIVEMQ_PERSISTENT_TOPIC="${ACTIVEMQ_PERSISTENT_TOPIC}<topic physicalName=\"${x}\" />"
	done
fi
if [ "${ACTIVEMQ_STATIC_QUEUES}X" != "X" ]; then
        QUEUES=$(echo ${ACTIVEMQ_STATIC_QUEUES} | tr ";" "\n")
        for x in ${QUEUES}
        do
                ACTIVEMQ_PERSISTENT_QUEUE="${ACTIVEMQ_PERSISTENT_QUEUE}<queue physicalName=\"${x}\" />"
        done
fi
if [ "${ACTIVEMQ_PERSISTENT_TOPIC}X" != "X" ] || [ "${ACTIVEMQ_PERSISTENT_QUEUE}X" != "X" ]; then
	sudo -u activemq -H sed 's/{{ACTIVEMQ_PERSISTENT_DESTINATION}}/'"<destinations>${ACTIVEMQ_PERSISTENT_QUEUE} ${ACTIVEMQ_PERSISTENT_TOPIC} </destinations>"'/' -i conf/activemq.xml
else 
	sudo -u activemq -H sed 's/{{ACTIVEMQ_PERSISTENT_DESTINATION}}/'""'/' -i conf/activemq.xml
fi

# We setting the wrapper.conf file (this is the main setting of wrapper)
sudo -u activemq -H sed 's/{{ACTIVEMQ_MIN_MEMORY}}/'"${ACTIVEMQ_MIN_MEMORY}"'/' -i bin/linux-x86-64/wrapper.conf
sudo -u activemq -H sed 's/{{ACTIVEMQ_MAX_MEMORY}}/'"${ACTIVEMQ_MAX_MEMORY}"'/' -i bin/linux-x86-64/wrapper.conf

# We fix some problem about right
chown -R activemq:activemq ${ACTIVEMQ_DATA}
chown -R activemq:activemq ${ACTIVEMQ_LOG}
chown -R activemq:activemq ${ACTIVEMQ_CONF}

case "$1" in
  start)
	/usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf    
    ;;
esac


exit 0
